services:
  balanceador:
    container_name: rustyx-balanceador
    hostname: rustyx-balanceador
    image: nginx:latest
    volumes:
      - ./scripts:/scripts
      - ./datos_contenedores:/datos_compartidos
      - ./web/html:/usr/share/nginx/html:ro
      - ./balanceador/nginx.conf:/etc/nginx/nginx.conf:ro
    command: >
      bash -c "
      apt-get update >/dev/null 2>&1 &&
      apt-get install -y procps >/dev/null 2>&1 &&
      chmod +x /scripts/recopilar_datos.sh &&
      nginx -g 'daemon off;' &
      while true;do /scripts/recopilar_datos.sh;sleep 5;done
      "
    ports:
      - "80:80"
    networks:
      - rustyx-network
    depends_on:
      - web1
      - web2

  web1:
    container_name: rustyx-web1
    hostname: rustyx-web1
    image: nginx:latest
    volumes:
      - ./scripts:/scripts
      - ./datos_contenedores:/datos_compartidos
      - ./web/html:/usr/share/nginx/html:ro
    command: >
      bash -c "
      apt-get update >/dev/null 2>&1 &&
      apt-get install -y procps >/dev/null 2>&1 &&
      chmod +x /scripts/recopilar_datos.sh &&
      nginx -g 'daemon off;' &
      while true;do /scripts/recopilar_datos.sh;sleep 5;done
      "
    networks:
      - rustyx-network

  web2:
    container_name: rustyx-web2
    hostname: rustyx-web2
    image: nginx:latest
    volumes:
      - ./scripts:/scripts
      - ./datos_contenedores:/datos_compartidos
      - ./web/html:/usr/share/nginx/html:ro
    command: >
      bash -c "
      apt-get update >/dev/null 2>&1 &&
      apt-get install -y procps >/dev/null 2>&1 &&
      chmod +x /scripts/recopilar_datos.sh &&
      nginx -g 'daemon off;' &
      while true;do /scripts/recopilar_datos.sh;sleep 5;done
      "
    networks:
      - rustyx-network

  db:
    container_name: rustyx-db
    hostname: rustyx-db
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rustyx
    volumes:
      - ./scripts:/scripts
      - ./datos_contenedores:/datos_compartidos
    command: >
      bash -c "
      apt-get update >/dev/null 2>&1 &&
      apt-get install -y procps >/dev/null 2>&1 &&
      chmod +x /scripts/recopilar_datos.sh &&
      docker-entrypoint.sh mariadbd &
      while true;do /scripts/recopilar_datos.sh;sleep 5;done
      "
    networks:
      - rustyx-network

networks:
  rustyx-network:
    driver: bridge
